[build]
  command = "npm run build"
  publish = ".next"
  base = "new-lunar/my-next-app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "new-lunar/my-next-app/netlify/functions"
