[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 8888

[functions]
  directory = "netlify/functions"

[context.production.environment]
  MONGODB_URI = "mongodb+srv://smartdivyanshu123_db_user:MHA0cSdMEwRcuFq0@cluster0.hwdh190.mongodb.net/"
  MONGODB_DB = "lunar"
